merge: Feature/auth
Team-Clim/clim-api-service pull request #2
Opened 2024-10-27 12:38 UTC by parktaesu123

## 열심히 구현한 기능들
- 회원 가입 기능
- 로그인 기능
- 이메일 인증 기능

2024-10-28 00:20 UTC, coehgns requested changes

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/api/AuthController.java
> +        signupService.signup(request, verificationCode);
회원가입을 진행할 때 인증된 이메일을 통해서 회원가입을 하게 되는데 인증 코드를 회원가입 인자로 받는 이유가 있을까요?

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/api/AuthController.java
> +    }
인증 코드를 발급 받는 로직은 또 다른 하나의 email 패키지로 빼서 그 안에서 작업 하시는게 나을 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/application/EmailService.java
EmailService도 마찬가지로 email 패키지로 빼서 리팩토링 해주시면 될 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/application/LoginService.java
> +                .orElseThrow(() -> UserNotFoundException.EXCEPTION);
UserFacade 사용하시면 코드가 더욱 간결해질 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/application/SignupService.java
> +        if (userRepository.findByEmail(request.getEmail()).isPresent()) {
userRepository 안에서 요청의 이메일이 존재하는지 확인하는 메서드를 하나 만드시면 좋을 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/application/SignupService.java
> +        }
이 로직도 SignupService 클래스에서 처리하기 보다는 email 패키지를 만들어서 처리하시는게 나을 것 같습니다.
그리고 회원가입을 할 때 회원가입을 진행하려고 하는 이메일이 인증되었는지 예외를 처리하는 로직을 작성해주세요.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/application/SignupService.java
> +        }
선생님 계정은 저희가 따로 생성하여 발급 받기로 하여서 학생 회원가입 로직만 작성하시면 될 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/application/VerificationCodeService.java
해당 로직도 email 패키지로 만들어서 작업해주세요.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/dao/RefreshTokenRepository.java
> +
@Repository 어노테이션을 붙여주세요.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/dao/RefreshTokenRepository.java
> +public interface RefreshTokenRepository extends JpaRepository<RefreshToken, String> {
현재 JpaRepository를 상속 받고 있는데 CrudRepository를 공부하셔서 적용하시면 좋을 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/global/config/SecurityConfig.java
> +                        .requestMatchers("/login", "/", "/auth/signup").permitAll()
authController 보면서 로그인 엔드포인트를 설정해주세요.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/dto/request/LoginRequest.java
> +    @NotBlank
@notblank 어노테이션의 message 속성을 사용하시면 좋을 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/dto/request/LoginRequest.java
> +    @NotBlank
@notblank 어노테이션의 message 속성을 사용하시면 좋을 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/dto/request/SignupRequest.java
> +    @Size(min = 8, max = 16, message = "비밀번호는 8~16글자 입니다.")
password 정규식을 사용해서 지정해주세요.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/dto/request/SignupRequest.java
> +    @NotBlank
@notblank 어노테이션의 message 속성을 사용하시면 좋을 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/dto/request/SignupRequest.java
> +    @NotBlank
@notblank 어노테이션의 message 속성을 사용하시면 좋을 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/dto/request/SignupRequest.java
> +    @NotBlank
@notblank 어노테이션의 message 속성을 사용하시면 좋을 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/dto/request/SignupRequest.java
> +    @NotBlank
@notblank 어노테이션의 message 속성을 사용하시면 좋을 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/dto/request/SignupRequest.java
> +    @NotBlank
@notblank 어노테이션의 message 속성을 사용하시면 좋을 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/dto/request/SignupRequest.java
> +    @NotBlank
@notblank 어노테이션의 message 속성을 사용하시면 좋을 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/user/dao/UserRepository.java
> +
@repository 어노테이션을 작성해주세요.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/user/dao/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, String> {
String을 Long으로 수정해주시면 될 것 같습니다.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/user/entity/User.java
> +    private String profileImgUrl;
현재 프로필 이미지 기능은 보류 상태입니다. 삭제해주세요.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/user/entity/User.java
> +    private UUID id;
UUID를 사용하신 이유가 있을까요?

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/global/security/auth/CustomUserDetailsService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("User Not Found"));
ErrorCode에서 작성한 예외로 수정해주세요.

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/global/config/RepositoryConfig.java
해당 클래스의 역할이 무엇인가요?

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/domain/user/exception/NotAuthenticatedException.java
> +public class NotAuthenticatedException extends RuntimeException {
상속을 RuntimeException으로 받는 이유가 있을까요?

2024-10-28 00:20 UTC, coehgns commented on src/main/java/com/example/climserver/global/config/JwtConfig.java
해당 클래스의 역할이 무엇인가요?

2024-10-28 01:24 UTC, parktaesu123 commented on src/main/java/com/example/climserver/global/config/RepositoryConfig.java
Redis와 JPA에서 둘다 bean이 생성되고 충돌하는 에러가 Repository에서 일어나서 Config로 따로 분리 처리를 해서 해결했습니다

2024-10-28 01:28 UTC, parktaesu123 commented on src/main/java/com/example/climserver/global/config/JwtConfig.java
Jwtproperties를 빈으로 등록하는 역할 입니다

2024-10-28 01:54 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/user/entity/User.java
> +    private UUID id;
한번 써보고 싶었고 데이터베이스 설계할 때 충돌 방지해줘서 썻습니다

2024-10-28 01:59 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/user/exception/NotAuthenticatedException.java
> +public class NotAuthenticatedException extends RuntimeException {
해당 에러는 프로그래밍 로직이여서 따로 명시하고 처리안해도 됩니다

2024-10-28 02:04 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/api/AuthController.java
> +        signupService.signup(request, verificationCode);
음 여러 이유가 입니다 신원확인 할때랑 스팸이나 해킹 방지가 가장 큰 이유입니다

2024-10-28 02:05 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/api/AuthController.java
> +        signupService.signup(request, verificationCode);
회원가입 로직에서 사용자 신원 확인 할 때 사용되고 여러 보안 문제를 해결해줍니다

2024-10-28 02:09 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/application/SignupService.java
> +        }
이거 회원가입로직 아닙니다
리펙토링 했어요

2024-10-28 02:10 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/dao/RefreshTokenRepository.java
> +public interface RefreshTokenRepository extends JpaRepository<RefreshToken, String> {
제가 알기로는 JpaRepository가 CrudRepository의 상위 개념으로 알고있습니다

2024-10-28 02:11 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/dao/RefreshTokenRepository.java
> +public interface RefreshTokenRepository extends JpaRepository<RefreshToken, String> {
jparepository안에 crud기능들이 다 있습니다

2024-10-28 02:12 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/dto/request/SignupRequest.java
> +    @Size(min = 8, max = 16, message = "비밀번호는 8~16글자 입니다.")
이건 일단 안할께요 클라선에서도 할 수 있으니까

2024-10-28 02:14 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/user/entity/User.java
> +    private String profileImgUrl;
음 이미 삭제 되어있습니다

2024-10-28 02:14 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/user/entity/User.java
> +    private String profileImgUrl;
이게 리펙토링 전이랑 후랑 섞여있어서 최신내용보다는 예전 내용들이 뜨네요...

2024-10-28 02:49 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/api/AuthController.java
> +        signupService.signup(request, verificationCode);
어떤 보안 문제가 있을까요?

2024-10-28 02:50 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/dao/RefreshTokenRepository.java
> +public interface RefreshTokenRepository extends JpaRepository<RefreshToken, String> {
그럼 사용하는 범위에 맞게 해주시면 좋을 것 같습니다.

2024-10-28 02:54 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/application/SignupService.java
> +        if (userRepository.findByEmail(request.getEmail()).isPresent()) {
음 이부분에 있어서는 따로 설명이 필요할것 같습니다

2024-10-28 02:55 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/application/SignupService.java
> +        if (userRepository.findByEmail(request.getEmail()).isPresent()) {
repository에는 findByEmail이 있고 if문으로 그부분에 대한 예외처리를 하는게 더 간편하지 않을까요??

2024-10-28 03:19 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/application/SignupService.java
> +        if (userRepository.findByEmail(request.getEmail()).isPresent()) {
근데 일단 따로 서비스 클래스를 파서 해놓긴 했습니다 코드가 좀 더 깔끔해지긴 하네요

2024-10-28 06:54 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/dto/request/LoginRequest.java
> +    @NotBlank
우선 이거는 안하겠습니다

2024-10-28 07:23 UTC, parktaesu123 commented on src/main/java/com/example/climserver/global/config/SecurityConfig.java
> +                        .requestMatchers("/login", "/", "/auth/signup").permitAll()
저 이거 아닙니다 리펙토링 다시 해놨어요 이거 옛날코드입니다

2024-10-29 02:38 UTC, coehgns commented on src/main/java/com/example/climserver/global/config/JwtConfig.java
Jwtproperties 클래스에서 @component를 사용해주시는게 나을 것 같습니다.

2024-10-29 02:38 UTC, coehgns commented on src/main/java/com/example/climserver/global/config/JwtConfig.java
해당 클래스 지우고 @Component 사용해주세요.

2024-10-29 02:38 UTC, coehgns commented on src/main/java/com/example/climserver/global/config/WebConfig.java
해당 클래스에 cors 설정을 해주시는게 나을 것 같습니다.
정적 리소스를 왜 처리하는지 알려주실 수 있나요?

2024-10-29 02:38 UTC, coehgns commented on src/main/java/com/example/climserver/domain/auth/email/application/VerifyVerificationCodeService.java
auth안에 email 패키지가 아닌 domain에서 email 패키지를 새로 만들어서 auth와 email을 완전히 분리해주세요.

2024-11-10 23:44 UTC, parktaesu123 commented on src/main/java/com/example/climserver/global/config/JwtConfig.java
저도 해당 어노테이션을 사용하려고 했었으나

2024-11-10 23:46 UTC, parktaesu123 commented on src/main/java/com/example/climserver/global/config/JwtConfig.java
그 어노테이션을 달면 자꾸 클래스이름에 빨간줄이 생기고 이 에러를 해결하면 @ConfigurationProperties이 어노테이션에 문제가 생겨서 JwtConfig로 빼서 해결하는게 가장 좋다는 결론을 내렸습니다

2024-11-10 23:46 UTC, parktaesu123 commented on src/main/java/com/example/climserver/global/config/JwtConfig.java
사용하는데 있어서 크게 문제가 없어서 이대로 유지해도 괜찮을 것 같습니다

2024-11-11 00:05 UTC, parktaesu123 commented on src/main/java/com/example/climserver/global/config/WebConfig.java
토큰이 비어있는 에러가 생겼을 때 해결하려고 시도했던 방법중 하나입니다

2024-11-11 00:06 UTC, parktaesu123 commented on src/main/java/com/example/climserver/global/config/WebConfig.java
삭제 하고 돌려보니 포스트맨 날릴때도 이상이 없어서 삭제 하였씁니다

2024-11-11 00:07 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/email/application/VerifyVerificationCodeService.java
438c100a06b13acc82955c84dd84b564f64beb4a

2024-11-11 00:07 UTC, parktaesu123 commented on src/main/java/com/example/climserver/global/config/WebConfig.java
b03ceb951e4bc034fcca715dd72a4f8091afd900

2024-11-11 13:27 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/api/AuthController.java
> +        signupService.signup(request, verificationCode);
정리 해볼께요

2024-11-11 13:29 UTC, parktaesu123 commented on src/main/java/com/example/climserver/domain/auth/api/AuthController.java
> +        signupService.signup(request, verificationCode);
인증코드를 회원가입 인자로 받는 이유는 이메일이 유효한지 확인하고 회원가입을 할 수 있는 상태인지 검증할 때 사용됩니다 보안적인 부분으로는 회원가입 진행중일때 다른 유저가 해당 이메일로 회원가입을 진행할 수 없도록 하기 위함이라고 볼 수 있습니다

2024-11-11 13:56 UTC, imhanseong approved these changes

2024-11-11 13:56 UTC, coehgns approved these changes

2024-11-12 00:25 UTC, merged